name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: bmartin5692/android-builder:latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Build APK
        run: |
          cd android_remote
          ./gradlew assembleRelease
        env:
          ANDROID_HOME: /opt/android-sdk-linux
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
      
      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: android_remote/app/build/outputs/apk/release/app-release.apk
